services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm start:dev
